### ISSUE TITLE
Placeholder in message

### ISSUE THREAD

**Issue by NormanLord** [Zrips/Residence#1042]
I want to show cmi's nickname in residence message.But there're only %player and %residence to use.
I hope you can add papi support in here.

**Comment by Zrips** [comment]
This would introduce quite a bit of issues by giving regular player access to all placeholders on your entire server without any real limitations. With this player would be able to use complex placeholders, or even those which can perform commands without big trouble, due to security risks I cant add support for it. 
What I can do is to add %playerDisplay which would output players display name which should show players nickname, tho keep in mind depending on your plugin which controls players display name it might include extra information like prefix, suffix and colors.
c86e3ede93cab61b4f85180343b3ebd8dbc4f00c

**Comment by NormanLord** [comment]
Displayname is what I want.

**Comment by NormanLord** [comment]
Hey,I forget to mention the owner here.
![image](https://github.com/Zrips/Residence/assets/129029618/aec68c2b-4513-4e99-83bc-a79c891eecc6)

It would be nice if you add it here too.

**Comment by Zrips** [comment]
owner display is more complicated thing as owner might not be online which prevents easy way to get his display name. Best thing we could have is to check if owner is online and use his display name, if he isint then use his recorded last name, but that would create some inconsistencies in how it all looks like.
At this moment considering some alternatives to have player database in CMILib which could store some general information about players which could be used at any point in time, but it might take some time if I decide to go this way for this thing to be usable.

**Comment by NormanLord** [comment]
When player join and leave, we should record the infomations he've possessed.If there's a method to listen to player's displayname changing ,then we record at that moment.
It's ok with me as there's too much work need to do to implement that little function.
There's a plugin called offlinepapi which records player's placeholders after I set that plugin to record some placeholders.It makes some placeholders available for offline players.
Here's that plugin.
https://github.com/handy-git/OfflinePapi
One shortcoming of the plugin is it would make many same records for one placeholder of one player.
Here are some records it writed.
![image](https://github.com/Zrips/Residence/assets/129029618/4d1e0e3e-a745-43e7-a687-562ca4062ecb)

That's all I want to say,just makes some opinions~~
