### ISSUE TITLE
[Request] Y limit on random teleportation

### ISSUE THREAD

**Issue by Wertik1206** [Zrips/Residence#174]
Hey, I'm not into GitHub, so if i mess something up, feel free to delete this/pm me.
Also, if it's already a feature, please contact me as I'm in need for this.

Request: Adding Y limit to per-world random teleportation system.
Reason: When random teleporting to Nether, sometimes it throws you on the top bedrock layer.

**Comment by Zrips** [comment]
in general Residence already takes into account nether world and picks different max Y value while looking for possible location. That teleportation on the roof can be due to some another plugin (or server itself) trying to place player in a safe spot when residence tries to teleport player some where relatively unsafe.
