### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by TheHooperSC** [Zrips/Residence#188]
Hello, I have a problem with your plug-in, the server is dropping my server because of the chunks, can you help me please?

error here: 

https://pastebin.com/RC6pmeXg

**Comment by EncryptSL** [comment]
Your plugins ?
Server version ?

When removed plugin Residence.jar ?  Still is this error ?

**Comment by TheHooperSC** [comment]
Plugins: [20:17:27 INFO]: Plugins (62): PlaceholderAPI, PlugMan, AntiWorldFly, ASCommands, AutoLapiz, CommandSpy, ChatReaction, PlayerReport, WorldEdit, Essentials, AgarthaLib, Voting, RandomTP, MessageAnnouncer, Votifier, AdvancedPortals, MVdWPlaceholderAPI, FastAsyncWorldEdit, EssentialsChat, PermissionsEx, FeatherBoard, RFChairs, Vault, ProtocolSupport, FakaHedaMinequery, PlotSquared, LWC, WorldGuard, AuctionHouse, ChestCommands, DreamFish, AddLight, ViaVersion, EssentialsSpawn, TitleManager, MarriageMaster, Jobs, Multiverse-Core, ProtocolLib, Citizens, KitBattle, IPortal, Residence, BattleLevels, UltimateCasino, TAB, SuperbVote, PyroFishing, Lottery, MineResetLite, ServerListPlus, AntiTab, ArmorStandTools, AuthMe, AntiCommandTab, HolographicDisplays, CitizensCMD, SkinsRestorer, LeaderHeads, MineResetLitePlus, LiteBans, ItemCases

Server version: 1.13 
I dont know because I have a lot of players to take away the plugin residence

**Comment by TheHooperSC** [comment]
But from hosting I was told it's a plugin residence

**Comment by smmmadden** [comment]
silly question, but this is for a test server and not a live production server right?  And also not a world that was created in a 1.12.2 or early version of Spigot?
I ask, because we are not recommending using 1.13 for live production since 1.13 will not be supported since 1.13.1 is out.  However, not all plugins are supporting 1.13 or 1.13.1 yet so most of us are still testing before we attempt at using it in production.

There may also be migration/upgrade issues for previous worlds to 1.13.x until they say 1.13.1 is final.

**Comment by EncryptSL** [comment]
I have 1.13 latest build and without problem on live server. But your world created in version 1.12 or 1.13. 
Residence Version 4.8.0.2. ProtocolSupport maybe is your problem.

**Comment by smmmadden** [comment]
RandomTP may be interfering with the res rt command if they made it that far but the errors are pointing to something scheduled thats firing perhaps a save of the residence files??  All 500+ lines of exceptions all occurred at 11:50AM which tells me, it tried repeatedly to succeed but failed.

ProtocolSupport (if using 4.28) shouldn't be the issue since it hasn't been updated for 1.13.x and I'm not seeing issues with it either.  Knowing the server and version as well as when the world was created is key to figuring out what's going on including knowing if this was an existing world attempted to be upgraded to 1.13 - which no one would recommend yet.

**Comment by Zrips** [comment]
45a73eb85ef87f808cfc8126dc9ed7cec4646416
