### ISSUE TITLE
dynmap issues

### ISSUE THREAD

**Issue by WHiZSTA** [Zrips/Residence#213]
the residence integration with dynmap is great, but it has 2 major flaws. when you click on subzones, it only tells you the parent. when dealing with towns that have plots as subzones it basically doesn't provide us info we need.

Also with 3d rendering turned on, it is still only displaying the subzones as a thin line rather than the proper volume. this is also important to display correctly as we will have residences on top of others,

![image](https://user-images.githubusercontent.com/18521070/46254069-8f4a2500-c457-11e8-93d5-a37e048f41c7.png)

**Comment by WHiZSTA** [comment]
A quick added idea, besides identifying what the sub-claim's name is, it would be useful to list who the renter is too if possible.

**Comment by Zrips** [comment]
Zones are not shown in 3d because DynMap seems to be broken for this feature or i cant see some obvious option to make it work...
Everything else should work how you want, subzones should appear if there are any in that area and you should see if its rentable, those will be in green color, and who is renting it if anyone is renting. 
is your map public? Could i have a look at it to have better idea whats going on?
