### ISSUE TITLE
/back command

### ISSUE THREAD

**Issue by Niko302** [Zrips/Residence#223]
/back command does not work on residences would you be able to make it possible for it to work?

**Comment by Oruss7** [comment]
Need `tp` flag to true

**Comment by Klamist** [comment]
To someone finding an answer like me:
I've searched a lot to find how to enable `/back` after `/res tp`, since the `/back` always skips the `/res tp` and only back to last `/home, /back, /warp`.
Well I find nothing, except here, and later I managed to find a "register-back-in-listener" set in config.yml of Essentials.
```
# If you set this to true any plugin that uses teleport will have the previous location registered.
register-back-in-listener: false
```
Set this to true, and it's able to back on res tp.
