### ISSUE TITLE
Feature request: Fly in residence.

### ISSUE THREAD

**Issue by zeuzi** [Zrips/Residence#303]
Add a option or permission that user can fly in their residence's and in the residence's they're in

**Comment by ZodoxMC** [comment]
hmm i think there is already a fly flag, not sure if it also handles "visitors" tho 
but i think it would be odd if you can set that all visitors can fly

but i guess you mean a "personal" instead of "residence" flag if someone can fly in residences, i think residences just takes care of residence flags
but on the other hand i think, if someone is allowed to fly in all residences he can also be allowed to fly everywhere or not?

**Comment by K4raM4rx** [comment]
> hmm i think there is already a fly flag, not sure if it also handles "visitors" tho
> but i think it would be odd if you can set that all visitors can fly
> 
> but i guess you mean a "personal" instead of "residence" flag if someone can fly in residences, i think residences just takes care of residence flags
> but on the other hand i think, if someone is allowed to fly in all residences he can also be allowed to fly everywhere or not?

nope lol i just want fly to be allowed for building but not to fly trough the whole world

**Comment by kroko1992** [comment]
a hired a coder to make an addon who will allow the owner to set fly and fly for trusted. is that something you need? once its done and tested i will upload on spigot :)

**Comment by K4raM4rx** [comment]
> a hired a coder to make an addon who will allow the owner to set fly and fly for trusted. is that something you need? once its done and tested i will upload on spigot :)

Yeah totally ill look into it, could you send me a message when / if its finished.

you can message me on k4ram4rx@gmail.com or on discord : K4raM4rx#1337

**Comment by Zrips** [comment]
Fly flag is already present, it will be disabled for regular users by default and you will have to enable it in flags.yml file if you want to allow players to change it in their residence.

**Comment by K4raM4rx** [comment]
@Zrips does that include visitors to be able to fly in somebodys plot
