### ISSUE TITLE
Residence With WorldGuard

### ISSUE THREAD

**Issue by SkyHeroesDada11** [Zrips/Residence#384]
Hello,

The Residence plugin does not take over the protection of WorldGuard, so that players can not build in their homes because worldguard prevents them, but if I remove the protection they can destroy the spawn, and then in the plugin Residence there to mark "(Optional) WorldGuard support" but how ? Pleaseeee

Plugin Residence : https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-14.11480/
Spigot 1.13.2

**Comment by SkyHeroesDada11** [comment]
??????????????

**Comment by kassadGLA** [comment]
Enabling WG support means that you cannot create residences intersecting with WG regions and nothing more. I generally can not understand your idea of using two plugins to protect a one region.

**Comment by SkyHeroesDada11** [comment]
> Enabling WG support means that you cannot create residences intersecting with WG regions and nothing more. I generally can not understand your idea of using two plugins to protect a one region.

I do not understand what you tell me ?? 
Example: I have a city and within houses, the city is claim by worldguard but I want players to buy homes in the city with Residences.
But they will not be able to because of worldguard, except that if I remove worldguard they will be able to destroy the city. 
I want to use the 2 plugins, but Residences must take the advantage on Worldguard

**Comment by Zrips** [comment]
You cant take over of another protection plugin. if you have WG which prevents block place event, then residence plugin will not help you out here. You can cancel events, you cant force them to be performed. You could simply protect your spawn with residence plugin alone, then set subzones which can be both or rented where players could build their houses. Having 2 protection plugins in one place is not a good idea.

**Comment by zainmz** [comment]
Sorry for re-opening, but I use 2 protection plugins for 2 different purposes on the same server. I was searching the internet for the same issue and found this. Hope it helps those who is looking for the answer to this question.

SOLUTION: Create a wg region where you want the residence to be and do
/rg flag <region> build allow
Then create the residence that is in the exact same area as the world guard region. Now people will only be able to use the residence if they own it. Also since it is a residence region you can use a [Rent] sign from residences signs which means people will not be able to build in the region only use what is there.
