### ISSUE TITLE
[BUG] Conflict between the plugin "Residence" and "ItemsAdder". (Please Help)

### ISSUE THREAD

**Issue by Deathroner** [Zrips/Residence#469]
**I start this ticket in "ItemsAdder" and "Residence".**

_ItemsAdder is a plugin that simulates a minecraft mod, and in this you will find vehicles such as planes, cars, among others._

**When boarding a vehicle in an area protected by "Residence", the following error is generated in the console:**

`[Server] ERROR POI data mismatch: never registered at BlockPosition{x=-4801, y=64, z=2432}`
`[Server] INFO Attempt to teleport dead player Deathroner_ restricted`

This had happened to me in another plugin called "Towny", but no solution was reached because it was not found what is causing the failure.

**Zrips**, Could you help us find fault with this?
I want to keep both plugins working on my server because I consider them very complete and stable; It is also annoying that I have to migrate my users to another plugin :(

**PS: When getting into a vehicle in an area protected by "Residence", it won't let me send messages or apply commands; the only solution is to re-enter the server, but the vehicles disappear.**

**Comment by Deathroner** [comment]
https://github.com/LoneDev6/ItemsAdder/issues/218

**Comment by Zrips** [comment]
This looks more like an issue from ItemsAdder plugin, as this could only be cause by faulty and inappropriate code when creating entities for one or other reason. I cant really help out without knowing code of that plugin, which should be looked up by developer of that plugin. Then he will determine cause of it and might fix it from his end or point out possible fix for ours. But at the end of day, this should be resolved from ItemsAdder end.

**Comment by LoneDev6** [comment]
Hello @Zrips 
does Residence has any check for entities? Armorstands and Slimes.

Thanks for the help

**Comment by LoneDev6** [comment]
Bump @Zrips

**Comment by Zrips** [comment]
@LoneDev6 
You will need to be more specific than this. About which checks are you talking here specifically? Entity damage? Interaction?

**Comment by LoneDev6** [comment]
Interaction

**Comment by Zrips** [comment]
There are some checks but again, specifics. What should be checked and in which conditions?

**Comment by LoneDev6** [comment]
I don't have any clue.
The only thing I know is that if users have Redidence installed they don't get vehicle Bossbar shown and they get stuck.
I think the problem could be in Residence mount checks if it has any

**Comment by Zrips** [comment]
What is the process to create this bug exactly? Like what item/action do i need to perform to create it?

**Comment by LoneDev6** [comment]
For what I understood they can trigger it doing:
- placing the vehicle
- recharging it using fuel (right click with coal item)
- right click with bare hands to mount it
you get stuck and server won't get your chat messages

**Comment by LoneDev6** [comment]
I can give you access to the plugin if you contact me via SpigotMC, so you can check if and when you have time

**Comment by Zrips** [comment]
My account on spigotmc is the same as here, Zrips. I can check that one out, but it looks to be issue with your specific handling of vehicles. Residence doesn't really do any nasty stuff or some funky things with packets, which seams to be the issue here if player is no longer visible by server when they send messages.

**Comment by LoneDev6** [comment]
I added you 👍 
I don't do strange thing with packets, they are real server entities, I really have no clue

**Comment by Zrips** [comment]
Ok. I mean... That's... Something. 
Installed your plugin, started server, bunch of errors, so i guess it doesn't work from first run, but well, tested out if error is there. It was. So decided to restart server, just to make sure that its not the issue with first run. Same issue, still getting error. So removed residence plugin and other none relevant ones, error still there. This is not residence issue, it cant be.
And side note, you have Protocollib dependency, which entire purpose is to do stuff with packets, so you are doing something with them or this error originates from somewhere else in your code. 
In general this error was reported before across minecraft in general, basic google search gives out quite few results related to this error
`[18:17:47 ERROR]: POI data mismatch: never registered at BlockPosition{x=802, y=71, z=-619}`

Tested on 1.16.1 paper 115 build with only: ItemsAdder, LightAPI, LoneLibs, LuckPerms, ProtocolLib
Try placing itemsadder:black_go_cart and you should get same exact error. 
So that's that. I cant fix something what is not caused by my plugin.

**Comment by LoneDev6** [comment]
This error has nothing to do with the bug, if you remove Residence you won't get stuck when riding the vehicle and you will see the Fuel bossbar correctly.
If you install Residence you won't see the Bossbar and you will get stuck after you ride the entity.
That's what this Github issue is about, not about the " POI data mismatch". This error is [normal ](https://hub.spigotmc.org/jira/browse/SPIGOT-5710)when a plugin cancels place event.

**Comment by Zrips** [comment]
Bossbar cant be hidden as those work as separate entities, atleast normally they do. As of testing bossbar works from your plugin while Residence is present.
" POI data mismatch" is not normal. Residence and other plugins cancel all types of place events left and right, none of them gives out this error, so you need to check your code and avoid this one.
Retested with residence and your plugins, everything seams to be working as it should, no glitches, i can enter gocart, ride with it around and so on, with OP or regular player. 
Side note, noticed that you can enter residences which should not allow player movement inside of it while you are in gocart. No PlayerMoveEvent event being fired?

**Comment by LoneDev6** [comment]
Mh... so basically you're saying that it works fine? XD damn, well probably it was a Spigot issue and was fixed in some previous updates. The user who reported these problems didn't answer here anymore so I think it's fixed and it's fine.

I think no PlayerMoveEvent is fired because I'm editing vehicle location not player one

Thanks for your testing, you were really kind.
Have a nice day

**Comment by Zrips** [comment]
@LoneDev6 
I cant say that it works fine, as you do have error message which at best scares people and they will think that something serious going on. Second, we have a way to enter residence where you should not be able to do so as you are not firing player move event when you change players location from one point to another. You need to fire player move event and check if its canceled or not, this is quite big thing for you to do. You can optimize this and fire this event only when you change block, so moving inside same block could avoid firing this event, but in general it NEEDS to be fired and you NEED to check if its canceled or not.

**Comment by LoneDev6** [comment]
The POI error has nothing to do with the problem.
Anyway to fix this issue you have to avoid removing monsters with custom name and/or invulnerable monsters as my SLIME is invulnerable and has custom name. I use the slime to create custom vehicles.

Thanks

**Comment by LoneDev6** [comment]
Here is your code to be changed: https://github.com/Zrips/Residence/blob/master/src/com/bekvon/bukkit/residence/listeners/ResidenceEntityListener.java#L535

Just add a check for invulnerability and you're done.

**Comment by 100petr** [comment]
@Zrips can you try fix it?

**Comment by 100petr** [comment]
@Zrips 

> Here is your code to be changed: https://github.com/Zrips/Residence/blob/master/src/com/bekvon/bukkit/residence/listeners/ResidenceEntityListener.java#L535
> 
> Just add a check for invulnerability and you're done.
