### ISSUE TITLE
[BUG] Levitating with blocks

### ISSUE THREAD

**Issue by Jirsaacek** [Zrips/Residence#471]
Hi, I recently found bug in residence plugin, I'll try to describe it as best as I can... :)
When player is in Residence, he can't build in, he is able to jump and quickly place blocks under his legs and stand on them, for other players it looks like he is levitating. He can see bugged blocks in the air and stand on them, but other players can't, and it looks like he is levitating/flying. I think that's kinda important, and it should be fixed as fast as possible, I'm sorry if i described it bad.
Thank you for reading :)

**Comment by Zrips** [comment]
its not a bug by itself, atleast not from side of residence. It looks more like a client/server miscommunication when player places block but block placement is canceled while data between player and server doesn't sync properly due to possible delay between them. Slightly moving around should bring player down.
