### ISSUE TITLE
/res list from console

### ISSUE THREAD

**Issue by Eredrim** [Zrips/Residence#53]
Hello,

I just write this ticket to ask you a very little feature : display the residences list when I type /res list playername in the console. This will allow me to make rcon based scripts.

**Comment by smmmadden** [comment]
That command is already available on the console as **/res listall**
Take a look at the Wiki page for all the commands and what they do.  **/res list** on the console won't work as you're not a player, so you need to do **/res listall** instead.  Are you using the latest version of Residence? Is it not working? If not, let us know what the server and version you are using as Spigot 1.11.2 works fine as well as Spigot 1.12 pre5 builds.

**Comment by Eredrim** [comment]
The command **/res listall** lists all residences which are created on the server. I need a command to list all residences for a specific player. That's why I would like to use **/res list <player>** from the console.
I use the latest Spigot and Residence version.

**Comment by smmmadden** [comment]
Did you even try to use /res list playername ?

**Comment by Eredrim** [comment]
Of course, and it doesn't work.

**Comment by smmmadden** [comment]
If it doesn't work:
1. What is the exact Spigot Version?
2. What is the exact Residence Plugin Version?
3. What Operating System & Version?
4. What Java Version are you using?
5. Is this the first time you tried it?
6. What permissions plugin are you using?
7. What message on the console is shown when you try using **/res list <player>** or **/res listall**
The fact I'm not able to reproduce on 1.11.2 and 1.12 implies something other than the plugin is preventing it from working.

**Comment by Eredrim** [comment]
1. git-Spigot-3fb9445-2b6c9f4 (MC: 1.11.2)
2. Residence 4.6.3.0
3. I don't know, I was hosted on a mutualised platform. I just know it is a linux-based system
4. Java 8
5. It is not the first time, I tried before with older versions and I already had the same problem
6. Essentials GroupManager
7. - When I type **/res list <player>**, I just have nothing neither in the command return nor in the logs. 
    - When I type **/res list** : "Nothing to show"
    - When I type **/res listall**, I have the full residences list

**Comment by smmmadden** [comment]
Thanks - this helps a lot.  Are you using the latest Java 8 version (1.8.0_131) or an older copy?  I know the versions before 101 were problematic but since fixed.  
Okay the fact you had the same problem previously says a lot.  It could be the Java version and/or Linux (though the latter is unlikely), the permissions are not there or another plugin is conflicting with this one.

For 7 and **/res list eredrim** you're saying nothing appears in the console, not even "Nothing to show"?

Have you checked the permissions in Group Manager for missing permission nodes?  Are you using [this version](https://www.spigotmc.org/resources/groupmanagerx.32280/) of Group Manager or an older copy?

Do you have access to the log files showing all the versions of other plugins starting up and loading?  That will help to see if some other plugin is interfering with this one.

For what it's worth, I moved away from Group Manager due to it not being updated in quite a while, though the GroupManagerX version was updated for 1.11.  I'm using [PermissionsEx](https://dev.bukkit.org/projects/permissionsex) and it is easier and being supported.

If you're unsure if you are using the latest versions of the plugins, [visit this page](https://www.spigotmc.org/wiki/spigot-1-11-plugin-compatibility-list/).

**Comment by Eredrim** [comment]
Thanks for your answer. I don't know what java version I have (because of the mutualised platform) but I will try on a local copy of my server to check if it is a java or linux problem.
For the command **/res list playername**, effectively I don't see anything at all, the response is empty if you prefer.

I don't really understand why you think it could be a permission plugin problem. The console was normally not affected by it and is considered like an op player, no ?

The version of groupmanager I use is one which was published by the essentialsX team, at the same time of their first builds. It works correctly and I don't have any error with it. But thanks for the sharing of GroupManagerX, I think I will try it soon.

**Comment by smmmadden** [comment]
np, the reason I stated it could be a permissions issue is if the residence.* permissions are not present, even the console won't know what to do with it and you mentioned previously it never worked.  When I used Essentials Group Manager, I never had this problem and always had results when running it in-game and on console.
Does /resadmin listall work?
And just to be sure, you have residences returning results in-game, right?
I'm confused that you don't know what version of Java it is when you have console access.  Do  you have access to get the server logs?  That would help isolate where the problem is. Thanks!

**Comment by Eredrim** [comment]
I had the time to do dome tests and I think I found the problem. With my specific hosting, I just have a RCON access to my server and the problem appears only if the command is type from the RCON. On my PC (in Windows) I made the following test with a copy of my server : 
- I typed the command **/res list playername** directly in the terminal, all worked everything, I sawed the residence list of the player.
- I typed the same command in RCON (with my local machine as target) and I got an empty line.

Otherwise, even if I don't have an ssh access (that's why I can't know the java version), I have an access to the server logs. Here is my starting log (please make a copy if you want to keep it, it will stay online only 1 day) : https://zerobin.net/?f173ad5ff1943149#G2ykSticHLo5Kb0YGA6Rum3/IRpBiKGZnjdiFZwcgPU=

**Comment by smmmadden** [comment]
that was it - RCON or Remote Console isn't the same as the direct console, so the commands would be limited.  It would be up to the server owner to enable additional features like running minecraft commands via RCON.  Glad you were able to figure it out.  :-)

**Comment by Eredrim** [comment]
I don't really understand your comment... I can run **any** Minecraft command from RCON, it runs perfectly. This is just this one which has a problem. The other residence commands work and the other plugins commands work too.

**Comment by smmmadden** [comment]
it could be just that part of the code Zrips will have to look at then.  Assuming you can use /stop /reload and all the other mc commands.  If you can stop/restart the server, then I would expect you can run java -version as well to get the Java version of the server right?

**Comment by Eredrim** [comment]
Unfortunately no because /stop and /reload are MC commands and java --version is a linux command. I just have a RCON terminal, not a SSH o_e. However, on my local tests (on Windows) I observed the same problems and the java version was 1.8.0_131.
