### ISSUE TITLE
Create New Residence NoCostForYBlocks BUG

### ISSUE THREAD

**Issue by AnateXP** [Zrips/Residence#573]
In config , NoCostForYBlocks is true , they will cost for x*y blocks , but NoCostForYBlocks is false they will cost for x*y*z blocks , but selection ( First selection Y - Seconed selection Y = 0 )

( X:0 Y:1 Z:0 , X:100 Y:1 Z:100) or ( X:0 Y:125 Z:0 , X:0 Y:125 Z:0 ) or ( X:x Y:100 Z:z , X:x Y:100 Z:z )
if twice selection Y is same

they are no cost ! free ! ( First selection Y - Seconed selection Y = 0 )
how to fix it ? I cant found in config.yml
Plugin Version : 4.9.1.9
Server Version : Paper version git-Paper-209 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1 SNAPSHOT)
Java Version : Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
Operating System : Microsoft Windows 10 2004 ( OS 19041.508 )

My English is not good , but problem is very fucked , please help me

**Comment by WhiteKing21** [comment]
I'm asking if this is not a bug in the [spigot discussion section for Residence](https://bit.ly/2TVL6gx).
The plugin seems to be multiplying x*y*z to calculate the cost but changing the formula to x*(y-1)*z so if we rent 1 block high zone no matter the size it will cost $0.

I will assume many ppl have 2 high areas or more as a minimum and therefore not dealing with this issue but we really want ppl to be able to rent (protect) just a chest because server prices for protections are very high due to server logistics and it seemed stable but with this change/bug/unwanted feature we will not be able to.

We really hope we can figure out a way to go back to older versions where this was working just fine. 
We'll be waiting for an answer on the matter.

We really appreciate the awesome work you are doing with this plugin, it is THE plugin to go when protecting on Minecraft.
Thank you

**Comment by Zrips** [comment]
a45086593097a79420674e2259ccd8460dde79da
