### ISSUE TITLE
Anchor flag is broken

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#605]
Hi, when i'm using anchor flag, it doesn't work and the anchor couldn't be opened outside residence (without any message) and neither in residence (where it spam that I don't have permission anchor even when I'm admin with * and resadmin permission.

**Comment by 100petr** [comment]
The same problem. I have a slimefun and fluffymachines addon on the server and I can't open BOTTOMLESS_FLUFFY_BARREL.
The problem is since the last update. 
![image](https://user-images.githubusercontent.com/29830635/101281811-a9b78000-37d1-11eb-97a9-51b2faa5005a.png)
![image](https://user-images.githubusercontent.com/29830635/101281815-af14ca80-37d1-11eb-91ae-7355623cc49f.png)
![image](https://user-images.githubusercontent.com/29830635/101281819-b50aab80-37d1-11eb-8fee-f213fea41e64.png)
![image](https://user-images.githubusercontent.com/29830635/101281827-bcca5000-37d1-11eb-9c09-15500e5aaa91.png)
![Screenshot_1](https://user-images.githubusercontent.com/29830635/101281850-d4a1d400-37d1-11eb-9af8-7a128ad11f17.png)
It is not possible to open it with all the permission (*) even to the owner of the residence.

**Comment by Zrips** [comment]
Tested on anchor inside own residence, some one elses residence and outside of it. Every action got recognized properly and player could interact with Anchor block properly. Could both of you test this with Residence only to make sure that this isint originating from another plugin which triggers anchor interact event with incorrect criteria?

**Comment by bobhenl** [comment]
Message is printed twice even when I have * permissions as mentioned 
![image](https://user-images.githubusercontent.com/18662086/101360276-b73a3c00-389d-11eb-9a13-a3d02d065ed8.png)
With default settings, clean version of plugin, etc...

**Comment by 100petr** [comment]
It looks like it's fixed after the update.

**Comment by bobhenl** [comment]
Even when you try it in residence? For me it's not.

**Comment by 100petr** [comment]
I forgot to answer. It really doesn't work, I don't know if I was out of residence or what.

**Comment by bobhenl** [comment]
I still can't open it cause I don't have flag anchor in residence... as player with resadmin permission, so wtf.
![image](https://user-images.githubusercontent.com/18662086/106646477-1494f580-658e-11eb-943e-238f2fdb1a6f.png)
