### ISSUE TITLE
Can,t create subzone 4.9.2.2

### ISSUE THREAD

**Issue by 9dolanla** [Zrips/Residence#638]
i used 4.9.2.2 can,t create subzone
I could create in previous versions

**Comment by 100petr** [comment]
what does it tell you?

**Comment by 9dolanla** [comment]
tell: Out of range must be less than 0
But i set 10 or more
The preset value just downloaded cannot be set either

**Comment by 100petr** [comment]
can you send your groups.yml?

**Comment by 9dolanla** [comment]
[GG.txt](https://github.com/Zrips/Residence/files/5878771/GG.txt)

**Comment by 100petr** [comment]
maybe ```SubzoneDepth: 0```
Default groups.yml: https://github.com/Zrips/Residence/blob/master/src/groups.yml
Try to change it

**Comment by 9dolanla** [comment]
![image](https://user-images.githubusercontent.com/77821158/105978274-537a0580-60cd-11eb-8663-5b0ca9610220.png)

**Comment by 9dolanla** [comment]
![image](https://user-images.githubusercontent.com/77821158/105982727-a4402d00-60d2-11eb-8f9a-ea31fa74a12d.png)

**Comment by Zrips** [comment]
You need to properly define subzone area, entire section in groups relating to subzones is missing as it defaults to 0. So you cant create actual subzone because you cant have them in general and selection cant be more than 0, as defined in groups file. Simply check Default group and you will see all possible options there.

**Comment by Zrips** [comment]
dd20afffa849e875f21df04a29014888a113244f
