### ISSUE TITLE
Huge problems after new version

### ISSUE THREAD

**Issue by naikyy** [Zrips/Residence#725]
Hello, there are some new problems after the newest version (4.9.3.8) - When I try to /res list <player>, it shows some residences but in some cases there is residence and error too: https://ctrlv.cz/shots/2021/05/29/5UgT.png

Next, when you try to set flags, there is just empty GUI: https://ctrlv.cz/shots/2021/05/29/EqTA.png

What to do, is it my problem?

**Comment by Zrips** [comment]
I need actual error message from your console

**Comment by naikyy** [comment]
The problem is that there are no errors but even when I tried to install Residence plugin on empty test server and tried to create a residence I had the same problem as you can see on screens.

**Comment by Zrips** [comment]
UI should not have had errors in console, but that message after you did /res list should have. In any case, released new version, try testing that one and check if issue got resolved

**Comment by naikyy** [comment]
Oh yeah, the thing with /res list is fixed after the newest version.

**Comment by naikyy** [comment]
By the way, I have an issue with one player. He says that he got like few days ago residence from player (by /res give), but from now, he doesnt have the residence. We have on the server max 1 residence per player and he has in (/res list) just residence with full permission from another player. Is it possible that the residence just got deleted because of 1 residence per player and the new function that residence where you have full permission is showed in /res list?

**Comment by Zrips** [comment]
Residence limitation only applies when you try to create new one or you get one from some one else, but it should never remove existing ones

**Comment by naikyy** [comment]
Okay, here are some new unique errors: https://pastebin.com/WrCD6Eph

Players lost some residences and I can see that there are some problems with saving in the URL I've sent you. There too some other problems, take a look on it.

**Comment by naikyy** [comment]
Also newest version: 4.9.3.9, some problems again related with res list.... https://pastebin.com/tkKUusTg

**Comment by naikyy** [comment]
Im sorry for spamming, but there are so many problems after the newest update and we are also server based on residences so it kinda hurts. Well, if you have version Residence4.9.3.7, the player have residence but he cant see it in /res list, he cant delete it by /res remove, he cant see some info /res info. Nothing works but atleast there is "invisible" residence, that player cant break blocks there and do the things. 

When I upgrade to the newest version, the invisible residence is gone too. So what to do now? Im stucked on version 4.9.3.7, so players can have atleast this "invisible" residence.

What I saw in log, there was error with saving the residences and all these residences were deleted in the newest version. Dunno.

**Comment by mercurialmusic** [comment]
Sorry I opened a new ticket before checking, but getting the same as @naikyy's most recent errors. Will paste that ticket/error here:

Welp... 4.9.3.9 started at least, but it seems to have corrupted half our residences. Thank goodness for backups! Ended up using your built in backups instead of our own, so thanks for that extra feature too -- was a little easier to get to rather than our massive tarballs.

Startup seems fine, but immediately after the first player logged it started going haywire. Included both startup and the error in the paste here: https://gist.github.com/mercurialmusic/3ba190ea9505afd9cdf15e5efbe8aba6

This is only a portion of the error - went on to infinity and beyond. Residence commands stopped working even for residences that seemed to still exist, but about half of the residences were missing, even for people online/server residences/didn't really seem to matter but might have been more about the age of the residence? Was kinda hard to tell because even new residences were affected. I don't think it was to do with the trusted group because even residences without additional users were affected.

Sorry to give you more -- I know this one has been driving you crazy. Thanks for your help!

**Comment by AngieC233** [comment]
Having the same issues, many player's residence are missing.  Similar errors showing here https://pastebin.com/aGJWWMWS ...Failed to save residence

**Comment by jurajplayercze** [comment]
I had same problem with residences. I just took file from "backup" and replaced it, so i saved like this their residences. But the problem with res GUI (/res set) is still up even i downgraded back to older version

**Comment by Zrips** [comment]
Updated plugin. Cause was determined and fixed, please update to latest version Residence4.9.3.10
