### ISSUE TITLE
Ability to place Red Mushroom, Brown Mushroom and Mushroom Stem Blocks when place = false

### ISSUE THREAD

**Issue by Baterka** [Zrips/Residence#862]
Players are able to place Red Mushroom, Brown Mushroom and Mushroom Stem Blocks when they do not have `place` flag permission. They cannot place other blocks except for those listed.

Tested on newest version 5.0.1.3 on 1.18.1 server.

**Comment by Baterka** [comment]
Any updates on this? Or can you @Zrips at least migrate project to Maven/Gradle so we can help you with it?

**Comment by Zrips** [comment]
There is no difference between placed block types, this includes mushroom blocks. Whats most likely happening is another plugin takes over block place event and reanables it after residence already disabled place event.
There isint Maven/Gradle currently, my knowledge about its setup is limited and due to this project containing multiple plugins makes it more complicated to get it working properly, will try to get a working version at some point.
