### ISSUE TITLE
Infinity size for res?

### ISSUE THREAD

**Issue by DOSEV5** [Zrips/Residence#888]
I didnt find way to make my residence infinity size. So is there a way to do this,l because in documentation and here is not writen?

**Comment by SickProdigy** [comment]
Believe this was answered in discord. The user was convinced infinity was a bad idea. Because if you want infinity, you might as well just asign /resadmin perms to default user. That would be the way to do it, and the user refused that method. So we setup a more legitimate block range of about 5k x 5k range, in the groups.yml, and he then asigned the group the default user and was able to get it working in a capacity that wouldn't let a single user destroy the server by defining 'infinite"

**Comment by Zrips** [comment]
There is no such thing as infinite residence, but there is global flag section which defines flags for all worlds or just defined one. Other than this you can usually bypass most of the plugins limitations by using /resadmin command, which will ignore any your personal limitations when it comes to residence size or money requirements.
