### ISSUE TITLE
Residence Fly bug

### ISSUE THREAD

**Issue by a37911187** [Zrips/Residence#906]
When players go to the nether then teleport back to the overworld. Their filght mode will be turned on. Is there any solution to this problem?

**Comment by Zrips** [comment]
Without any actual information its really hard to say anything about this issue. This can be caused by miss configuration of Residence plugin or another plugin changing players fly mode, including multiverse type plugins. Would suggest to run test server with Residence only with default config files to make sure that issue you currently experience actually persists.
