### ISSUE TITLE
[Error] The incoming YAML document exceeds the limit

### ISSUE THREAD

**Issue by TenkyuChimata** [Zrips/Residence#947]
https://github.com/PaperMC/Paper/issues/8388
Server version: Paper 1.19.2-173
Residence version: 5.0.3.0
CMILib version: 1.2.3.6

https://paste.ubuntu.com/p/62PTJncJQG/

**Comment by Zrips** [comment]
Will be addressing this with some temporary solution. With latest minecraft versions yaml file size got limited to 3MB which causes some issues due to how residence plugin saves residences. Best solution is to keep using slightly older minercraft version which doesn't have this limitation put in place. 
5965d93729a83f66acc700c337eebb1ea80ed621

**Comment by Zrips** [comment]
a3cd3c9d0f4c920e4a4388395aa25cc7ed0219b3
