### ISSUE TITLE
Dropping armor in residence

### ISSUE THREAD

**Issue by daniel-skopek** [Zrips/Residence#998]
If I drop armor I'm wearing in a residence where dropping items is disabled (and I have a full inventory), the dropped armor disappears.

**Comment by Zrips** [comment]
Due to how this event being handled on server side can't really do much here to solve it as we are not getting any indication of item being thrown from armor slot, best case would be to add automatic armor equipment action when inventory cant handle thrown armor and place it into armor slot, but that would introduce other issues down the road. Will keep this issue in mind, but at the moment there is no good solution for it.
